### ISSUE TITLE
[question] How to deserialize json-object to an array of a type?

### ISSUE THREAD

**Issue by denis-shevchenko** [shakilsiraj/json-object-mapper#1]
I try deserialize my json-object like this

>         return this.http.get(url, { search: params })
>             .map(response => <Event[]>ObjectMapper.deserialize(Event[], response.json()));

but the follow error message has been thrown by webpack 

> You may need an appropriate loader to handle this file type.
> |         return this.http.get(url, { search: params })
> |             .map(function (response) { return json_object_mapper_1.ObjectMapper.deserialize(event_class_1.Event[], response.json()); });
> |     };
> |     return StageService;

Is it not possible, or what i doing wrong?

**Comment by shakilsiraj** [comment]
Hi there,

Array type at the root level is not supported yet. This is due to the fact that array type requires the type to be specified in the @JsonProperty decorator. So, what you are trying to do will not work at this point.

You can create a parent object and tie the array to it:

```
class Event{
....
}

class EventsArray{
 @JsonProperty({ type: Event })
  eventsArray: Event[] = undefined;
}
```

Then you can deserialize it as:

```
<EventsArray>ObjectMapper.deserialize(EventsArray, response.json())
```

Note that you will need to modify your JSON structure a little bit to cater for that.

Hope that helps

**Comment by shakilsiraj** [comment]
Ok, I think it's an important feature that got missed out. Please upgrade to release 1.3.0 where I have added a new function:

`ObjectMapper.deserializeArray(Type, Object) => Type[]`

In your case it should be something like:

`return this.http.get(url, { search: params })
        .map(response => <Event[]>ObjectMapper.deserializeArray(Event, response.json()));`


I have added a couple of unit tests for it as well.
